##
# Python project makefile.
##
.SHELL := bash
MAKEFLAGS += --warn-undefined-variables
#.SHELLFLAGS := -euo pipefail -c
.DEFAULT_GOAL := none

THIS_MAKEFILE := $(abspath $(firstword $(MAKEFILE_LIST)))
THIS_MAKEFILE := `python3 -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' ${THIS_MAKEFILE}`
SRC_ROOT := $(shell dirname ${THIS_MAKEFILE})

# WARNING: these vars must come before the includes
PYPI_PROJECT_NAME:=pynchon

# # Makefile includes
# MAKE_INCLUDES_DIR := ${SRC_ROOT}/.makefiles
# include ${MAKE_INCLUDES_DIR}/Makefile.base.mk
# include ${MAKE_INCLUDES_DIR}/Makefile.python.mk

## BEGIN: entrypoints for CI/CD stages
init:
	$(call _announce_target, $@)
	set -x \
	; pip install --quiet -e .[dev] \
	; pip install --quiet -e .[testing] \
	; pip install --quiet -e .[lint] \
	; pip install --quiet -e .[publish]

build:
	python -m build
version:
	@python setup.py --version
clean: python-clean pypi-clean tox-clean
pypi-clean:
	$(call _announce_target, $@)
	set -x \
	&& rm -f tmp.pypi* dist/* \
	&& rm -rf src/*.egg-info/
pypi-release: clean
	PYPI_RELEASE=1 make build
	twine upload \
	--user elo-e \
	--password `secrets get /elo/pypi/elo-e` \
	dist/*
smoke-test:
	pynchon gen cli click \
	--module pynchon.bin --command entry \
	--format markdown

push:
	make pypi-push pep440-describe-push

static-analysis: #announce-section-static-analysis
	tox -e static-analysis

test-integrations: announce-section-python-integration-tests
	$(call _announce_target, $@)
	tox $${tox_args:-} -e itest

test-units: announce-section-python-unit-tests
	$(call _announce_target, $@)
	tox $${tox_args:-} -e utest

test:
	@# NB: tox tries to decide whether to refresh venvs,
	@# but doesn't always get it right.  the test-* targets above are
	@# naive, but using this target ensures recreation for test-venvs.
	tox_args=--recreate \
	make test-units test-integrations

itest: test-integrations
utest: test-units

normalize:
	@# Uses tox to normalize code with autopep8.
	@# This helps to satisfy the linter, which by default is strict.
	$(call _announce_target, $@)
	tox -e normalize

.PHONY: docs
docs:
	$(call _announce_target, $@)
	set -x \
	&& mkdir -p docs/api \
	&& mkdir -p docs/cli \
	&& echo "\
	## Autogenerated \
	\n\nversion=\``make pep440-version`\` \
	\n\nhash=\``git rev-parse HEAD`\` \
	\n\npynchon_version=\``pynchon --version`\`" \
	> docs/VERSIONS.md \
	&& pynchon gen api toc \
	--format markdown \
	--package ${PYPI_PROJECT_NAME} \
	--output docs/api/README.md \
	&& pynchon project entrypoints \
	-f setup.cfg --format markdown \
	--output docs/cli/entry-points.md \
	&& pynchon gen cli click \
	--format markdown --name pynchon.bin:entry \
	--output docs/cli/README.md

pip-purge: python-require-pipenv
	@# Purges all dependencies from the currently active virtualenv
	$(call _announce_target, $@)
	set -x \
	&& pipenv uninstall --all --quiet

python-require-pipenv:
	@# Installs pipenv[0] if not present.
	@# This is sometimes useful even if the project doesn't use a Pipfile..
	@# see `python-pip-purge` target.
	$(call _announce_target, $@)
	pip freeze | grep pipenv \
	&& ( \
		printf '$(COLOR_GREEN)Detected pipenv is already present.$(NO_COLOR)\n' 1>&2 \
	) \
	|| ( \
		printf '$(COLOR_GREEN)Detected pipenv is missing. Installing it..$(NO_COLOR)\n' 1>&2 \
		&& pip install pipenv==2022.10.12 \
)
python-normalize: assert-src
	@# NB: most projects should really be doing this with a tox target,
	@# but this is still useful for handling things like scripts which are
	@# missing tox project boilerplate.
	make python-enumerate > /dev/null \
	&& ( \
		make python-enumerate \
		| xargs autopep8 --in-place) \
	|| printf "$(COLOR_YELLOW)WARNING:$(NO_COLOR) no python source files found in $${src} folder \n" > /dev/stderr

python-clean:
	@#
	$(call _announce_target, $@)
	@find . -name '*.pyc' -delete
	find . -name  __pycache__ -delete

tox-clean:
	@# Cleans tmp-dirs for tox
	$(call _announce_target, $@)
	find . -type d -name .tox | xargs -n1 -I% bash -x -c "rm -rf %"
