##
# Python project makefile.
##
.SHELL := bash
MAKEFLAGS += --warn-undefined-variables
# .SHELLFLAGS := -euo pipefail -c
.DEFAULT_GOAL := none

THIS_MAKEFILE := $(abspath $(firstword $(MAKEFILE_LIST)))
THIS_MAKEFILE := `python3 -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' ${THIS_MAKEFILE}`
SRC_ROOT := $(shell dirname ${THIS_MAKEFILE})

NO_COLOR:=\033[0m
COLOR_GREEN=\033[92m

PYPI_PROJECT_NAME:=pynchon


init:
	$(call _announce_target, $@)
	set -x \
	; pip install --quiet -e .[dev] \
	; pip install --quiet -e .[testing] \
	; pip install --quiet -e .[lint] \
	; pip install --quiet -e .[publish]

.PHONY: build
build: clean
	export version=`python setup.py --version` \
	&& (git tag $$version \
	|| printf 'WARNING: Failed to git-tag with release-tag (this is normal if tag already exists).\n' > /dev/stderr) \
	&& printf "# WARNING: file is maintained by automation\n\n__version__ = \"$${version}\"\n\n" \
	| tee src/${PYPI_PROJECT_NAME}/_version.py \
	&& python -m build

version:
	@python setup.py --version

clean:
	rm -rf tmp.pypi* dist/* build/* \
	&& rm -rf src/*.egg-info/
	find . -name '*.pyc' -delete
	find . -name  __pycache__ -delete
	find . -type d -name .tox | xargs -n1 -I% bash -x -c "rm -rf %"

pypi-release: clean
	PYPI_RELEASE=1 make build \
	&& twine upload \
	--user elo-e \
	--password `secrets get /elo/pypi/elo-e` \
	dist/*

release: normalize static-analysis test docs pypi-release

static-analysis:
	tox -e static-analysis

test-integrations:
	tox $${tox_args:-} -e itest

test-units:
	tox $${tox_args:-} -e utest

test:
	@# NB: tox tries to decide whether to refresh venvs,
	@# but doesn't always get it right.  the test-* targets above are
	@# naive, but using this target ensures recreation for test-venvs.
	tox_args=--recreate \
	make test-units test-integrations

itest: test-integrations
utest: test-units

normalize:
	@# Uses tox to normalize code with autopep8.
	@# This helps to satisfy the linter, which by default is strict.
	tox -e normalize

.PHONY: docs
docs:
	set -x \
	&& mkdir -p docs/api \
	&& mkdir -p docs/cli \
	&& echo "\
	## Autogenerated \
	\n\nversion=\``make pep440-version`\` \
	\n\nhash=\``git rev-parse HEAD`\` \
	\n\npynchon_version=\``pynchon --version`\`" \
	> docs/VERSIONS.md \
	&& pynchon gen api toc \
	--format markdown \
	--package ${PYPI_PROJECT_NAME} \
	--output docs/api/README.md \
	&& pynchon project entrypoints \
	-f setup.cfg --format markdown \
	--output docs/cli/entry-points.md \
	&& pynchon gen cli click \
	--format markdown --name pynchon.bin:entry \
	--output docs/cli/README.md

pip-purge: python-require-pipenv
	@# Purges all dependencies from the currently active virtualenv
	set -x \
	&& pipenv uninstall --all --quiet

python-require-pipenv:
	@# Installs pipenv[0] if not present.
	@# This is sometimes useful even if the project doesn't use a Pipfile..
	@# see `python-pip-purge` target.
	pip freeze | grep pipenv \
	&& ( \
		printf '$(COLOR_GREEN)Detected pipenv is already present.$(NO_COLOR)\n' 1>&2 \
	) \
	|| ( \
		printf '$(COLOR_GREEN)Detected pipenv is missing. Installing it..$(NO_COLOR)\n' 1>&2 \
		&& pip install pipenv==2022.10.12 \
)
python-normalize: assert-src
	@# NB: most projects should really be doing this with a tox target,
	@# but this is still useful for handling things like scripts which are
	@# missing tox project boilerplate.
	make python-enumerate > /dev/null \
	&& ( \
		make python-enumerate \
		| xargs autopep8 --in-place) \
	|| printf "$(COLOR_YELLOW)WARNING:$(NO_COLOR) no python source files found in $${src} folder \n" > /dev/stderr
