name: Publish Docker image

on:
  release:
    types: [published]
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
      - '**.md.j2'
      - '**.png'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build
        run: make build.docker
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        # uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        uses: docker/metadata-action@v5
        with:
          images: robotwranglers/pynchon
        tags: type=sha
      - name: Build and push Docker image
        # uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          # tags: robotwranglers/pynchon:latest
          labels: ${{ steps.meta.outputs.labels }}
          tags: robotwranglers/pynchon:latest ${{ steps.meta.outputs.tags }}